# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Adam K
tagline:          'Adam Kowalczyk - Web Developer'
description:      'Adam Kowalczyk'
description2:     'Web Developer'
url:              http://adamkowalczyk.github.io
baseurl:          /

email:            adamkowalczyk@gmail.com


author:
  name:           'Adam Kowalczyk'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/adamkowalczyk
